services:
  traefik:
    image: traefik:v3.0
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # No deploy section, so not used in production

  easymeals.ui:
    labels:
      - "traefik.http.routers.ui.rule=Host(`localhost`)"
      - "traefik.http.services.ui.loadbalancer.server.port=3000"
      - "traefik.http.routers.ui.entrypoints=web"

  easymeals.api:
    labels:
      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.entrypoints=web"