
services:
  easymeals.ui:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - easymeals.api
      
  easymeals.api:
    build:
      context: .
      dockerfile: apps/api/src/EasyMeals.Api/Dockerfile
    ports:
      - "8080:8080"
      # - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081

  easymeals.recipe-engine:
    build:
      context: .
      dockerfile: apps/recipe-engine/src/EasyMeals.RecipeEngine/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development